# Generated by Django 3.1.3 on 2021-03-20 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesiones',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basemodel')),
                ('titulo', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Titulo',
            },
            bases=('base.basemodel',),
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basemodel')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('monotributista', models.BooleanField(default=True)),
                ('profesion_personas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nuevo.profesiones', verbose_name='Profesion')),
            ],
            options={
                'verbose_name': 'Personas',
            },
            bases=('base.basemodel',),
        ),
    ]
